force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/FromEmail__c.field-meta.xml
<CustomField>
    <fullName>FromEmail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Drivers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drivers__c/fields/PhoneNo__c.field-meta.xml
<CustomField>
    <fullName>PhoneNo__c</fullName>
    <label>PhoneNo</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/Shipment_Package__c.object-meta.xml
<CustomObject>
    <label>ShipmentPackage</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>Shipment_Package Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ShipmentPackages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Package__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>All Shipments</relationshipLabel>
    <relationshipName>ShipmentPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>ShipmentPackages</relationshipLabel>
    <relationshipName>ShipmentPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Packed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HandlerNotifications.cls
public class HandlerNotifications {
    public static void NotificationBody(List<Shipment_Package__c> OldShipmentval,List<Shipment_Package__c> NewShipmentval){
        String oldStatusVal;
        String newStatusVal;
        String Name;
        String Email;
        Set<Id> customerID=new Set<Id>();
        Set<Id> DriverID = new Set<Id>();
        Drivers__c driver;
        
        //loop over the shipment 
        //check the status and Driver assigned to it
        for(Shipment_Package__c ship:NewShipmentval){
            newStatusVal = ship.Status__c;
            customerID.add(ship.Customer__c);
            
            if(ship.Driver__c !=null){
                DriverID.add(ship.Driver__c);
                driver=[Select Name,PhoneNo__c from Drivers__c where ID IN:DriverID limit 1];
            }
        }
      	//query the customer information for the shipments
        Customer__c customer=[Select Name,FromEmail__c from Customer__c where ID IN:customerID limit 1];
        Name=customer.Name;
        Email=customer.FromEmail__c;
        

		for(Shipment_Package__c oldship: OldShipmentval){
            oldStatusVal=oldship.Status__c;
        } 
        //Notify the customer about there Orders
        if(oldStatusVal != newStatusVal){
            ShipmentStatusNotification(newStatusVal,Name,Email);
        }
       
        // notify the customer about the driver assigned to the shipment
        if(driver !=null){
            DriverAssigned(driver.Name,Email);
        }
    }
    
    private static void ShipmentStatusNotification(String newStatusVal,String Name,String Email){
        String subject='Shipment Status';
        String body = 'Hello '+Name+' Your Order has been ' + newStatusVal;
        
		EmailManager.sendMail(Email,body,subject);        
    }
    
    private static void DriverAssigned(String driverName,String Email){
        String subject ='your order reached';
        String body = 'Hello' + ' Your Order has been reached the Hub, will be Delivered by ' + driverName;
        EmailManager.sendMail(Email,body,subject);
    }
}