force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/FromCity__c.field-meta.xml
<CustomField>
    <fullName>FromCity__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FromCountry__c.field-meta.xml
<CustomField>
    <fullName>FromCountry__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FromEmail__c.field-meta.xml
<CustomField>
    <fullName>FromEmail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FromPhone__c.field-meta.xml
<CustomField>
    <fullName>FromPhone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FromPinCode__c.field-meta.xml
<CustomField>
    <fullName>FromPinCode__c</fullName>
    <label>PinCode</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FromState__c.field-meta.xml
<CustomField>
    <fullName>FromState__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FromStreet__c.field-meta.xml
<CustomField>
    <fullName>FromStreet__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ReceivingName__c.field-meta.xml
<CustomField>
    <fullName>ReceivingName__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToCity__c.field-meta.xml
<CustomField>
    <fullName>ToCity__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToCountry__c.field-meta.xml
<CustomField>
    <fullName>ToCountry__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToEmail__c.field-meta.xml
<CustomField>
    <fullName>ToEmail__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToPhone__c.field-meta.xml
<CustomField>
    <fullName>ToPhone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToPinCode__c.field-meta.xml
<CustomField>
    <fullName>ToPinCode__c</fullName>
    <label>PinCode</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToState__c.field-meta.xml
<CustomField>
    <fullName>ToState__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/ToStreet__c.field-meta.xml
<CustomField>
    <fullName>ToStreet__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Drivers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drivers__c/fields/PhoneNo__c.field-meta.xml
<CustomField>
    <fullName>PhoneNo__c</fullName>
    <label>PhoneNo</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ShipmentPackage</label>
    <referenceTo>Shipment_Package__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/Shipment_Package__c.object-meta.xml
<CustomObject>
    <label>ShipmentPackage</label>
    <nameField>
        <displayFormat>SPN-{0000}</displayFormat>
        <label>Shipment_Package Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ShipmentPackages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Package__c/fields/Content_Value__c.field-meta.xml
<CustomField>
    <fullName>Content_Value__c</fullName>
    <label>Content Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>All Shipments</relationshipLabel>
    <relationshipName>ShipmentPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>ShipmentPackages</relationshipLabel>
    <relationshipName>ShipmentPackages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Package_Content__c.field-meta.xml
<CustomField>
    <fullName>Package_Content__c</fullName>
    <label>Package Content</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fast Day</fullName>
            </value>
            <value>
                <fullName>Normal Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Packed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Package__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight in kg</description>
    <label>Weight</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestShipmentsTrigger.cls
@isTest
public class TestShipmentsTrigger {
    
    @testSetup
    static void setup(){
        Customer__c cust = new Customer__c(
            Name='Suraj Rathod',
            FromEmail__c='surajrathod999@gmail.com',
            FromCity__c='Akola',
            FromCountry__c='INDIA',
            FromPhone__c='2323232323',
            FromPinCode__c=444004,
            FromState__c='Maharashtra',
            FromStreet__c='New Khetan Nagar Kaulkhed',
            
            ReceivingName__c='Sujita Rathod',
            ToEmail__c='surajrathod999@gmail.com',
            ToCity__c='Pune',
            ToCountry__c='INDIA',
            ToPhone__c='7878787878',
            ToPinCode__c=411047,
            ToState__c='Maharashtra',
            ToStreet__c='New kaveri complex'
        );
        insert cust;
    }
    
    @isTest
    static void insertShipmentCreateQuotationNormalDeliveryTest(){
        Customer__c cust=[Select Id from Customer__c];
        
        Shipment_Package__c shipment=new Shipment_Package__c(
            Package_Content__c='Product',
            Shipment_Type__c='Normal Delivery',
            Customer__c=cust.Id,
            Content_Value__c=343,
            Weight__c=23
        );
        insert shipment;
        //check if shipment related to quotation inserted
        Quotation__c quot =[Select Package__c from Quotation__c];
        system.assertEquals(quot.Package__c, Shipment.Id);
        
    }
    @isTest
    static void insertShipmentCreateQuotationFastDeliveryTest(){
        Customer__c cust=[Select Id from Customer__c];
        
        Shipment_Package__c shipment=new Shipment_Package__c(
            Package_Content__c='Document',
            Shipment_Type__c='Fast Day',
            Customer__c=cust.Id,
            Content_Value__c=347,
            Weight__c=23
        );
        insert shipment;
        //check if shipment related to quotation inserted
        Quotation__c quot =[Select Package__c from Quotation__c];
        system.assertEquals(quot.Package__c, Shipment.Id);
    }
    
    @isTest
    static void NotificationTest(){
        Customer__c cust=[Select Id from Customer__c];
        Drivers__c dri=new Drivers__c(
        	Name='Sriraj chavan',
            PhoneNo__c='232323232'
        );
        insert dri;
        Shipment_Package__c shipment=new Shipment_Package__c(
            Package_Content__c='Document',
            Shipment_Type__c='Fast Day',
            Customer__c=cust.Id,
            Content_Value__c=347,
            Weight__c=23
        );
        insert shipment;
        shipment.Status__c='Packed';
        shipment.Driver__c=dri.Id;
        update shipment;
    }
}